# Runal Gavade TE-05
# Assignment 1

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('iris.csv')

In [3]:
df = pd.DataFrame(df)

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [6]:
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [7]:
df.sample()

    sepal_length  sepal_width  petal_length  petal_width     species
75           6.6          3.0           4.4          1.4  versicolor

In [8]:
df.sample(5)

     sepal_length  sepal_width  petal_length  petal_width     species
69            5.6          2.5           3.9          1.1  versicolor
120           6.9          3.2           5.7          2.3   virginica
40            5.0          3.5           1.3          0.3      setosa
96            5.7          2.9           4.2          1.3  versicolor
109           7.2          3.6           6.1          2.5   virginica

In [9]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [10]:
df.shape

(150, 5)

In [11]:
df[10:21]

    sepal_length  sepal_width  petal_length  petal_width species
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa

In [12]:
specific_data = df[["sepal_length","species"]]
print(specific_data)

     sepal_length    species
0             5.1     setosa
1             4.9     setosa
2             4.7     setosa
3             4.6     setosa
4             5.0     setosa
..            ...        ...
145           6.7  virginica
146           6.3  virginica
147           6.5  virginica
148           6.2  virginica
149           5.9  virginica

[150 rows x 2 columns]

In [13]:
df.iloc[5]

sepal_length       5.4
sepal_width        3.9
petal_length       1.7
petal_width        0.4
species         setosa
Name: 5, dtype: object

In [14]:
df.loc[df["species"]=="Iris-setosa"]

Empty DataFrame
Columns: [sepal_length, sepal_width, petal_length, petal_width, species]
Index: []

In [15]:
df["species"].value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [16]:
sep_len_sum = df["sepal_length"].sum()
sep_len_mean = df["sepal_length"].mean()
sep_len_median = df["sepal_length"].median()
sep_len_min = df["sepal_length"].min()
sep_len_max = df["sepal_length"].max()

print("Sepal Length properties:\n")
print("Sum: {}, Mean: {}, Median{}, Min: {}, Max: {}".format(
    sep_len_sum, sep_len_mean, sep_len_median, sep_len_min, sep_len_max
))

Sepal Length properties:

Sum: 876.5, Mean: 5.843333333333334, Median5.8, Min: 4.3, Max: 7.9

In [17]:
df.isnull()

     sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

In [18]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [19]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\milin\anaconda3\lib\site-packages (1.3.0)
Requirement already satisfied: numpy>=1.17.3 in c:\users\milin\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in c:\users\milin\anaconda3\lib\site-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in c:\users\milin\anaconda3\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\milin\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Note: you may need to restart the kernel to use updated packages.

In [20]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [21]:
df["petal_length"] = df["petal_length"].astype(int)

In [22]:
df["petal_length"] = df["petal_length"].astype(float)

In [23]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.306667     1.198667
std        0.828066     0.433594      1.772068     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.000000     0.300000
50%        5.800000     3.000000      4.000000     1.300000
75%        6.400000     3.300000      5.000000     1.800000
max        7.900000     4.400000      6.000000     2.500000

In [24]:
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
min_max_scaler = MinMaxScaler()

In [25]:
x = df.iloc[:,:4]

In [26]:
x_scaled = min_max_scaler.fit_transform(x)
df_normalized = pd.DataFrame(x_scaled)
df_normalized

            0         1    2         3
0    0.222222  0.625000  0.0  0.041667
1    0.166667  0.416667  0.0  0.041667
2    0.111111  0.500000  0.0  0.041667
3    0.083333  0.458333  0.0  0.041667
4    0.194444  0.666667  0.0  0.041667
..        ...       ...  ...       ...
145  0.666667  0.416667  0.8  0.916667
146  0.555556  0.208333  0.8  0.750000
147  0.611111  0.416667  0.8  0.791667
148  0.527778  0.583333  0.8  0.916667
149  0.444444  0.416667  0.8  0.708333

[150 rows x 4 columns]

In [27]:
label_encoder = LabelEncoder()
df["species"] = label_encoder.fit_transform(df["species"])

In [28]:
df["species"].unique()

array([0, 1, 2])

In [29]:
merged_df = pd.concat([df["species"], df_normalized], axis=1)

In [30]:
merged_df.head()

   species         0         1    2         3
0        0  0.222222  0.625000  0.0  0.041667
1        0  0.166667  0.416667  0.0  0.041667
2        0  0.111111  0.500000  0.0  0.041667
3        0  0.083333  0.458333  0.0  0.041667
4        0  0.194444  0.666667  0.0  0.041667